title: Sense HAT cheerlights
hero_image: images/banner.png
description: Tweet a colour to light up your Sense HAT!
listed: false
copyedit: false
version: 4.1
last_tested: 2018-11-20
steps:
  - title: Introduction
  - title: Code and colours
  - title: Cheerlights
  - title: Challenges
